post http://localhost:3000/register 
Content-Type: application/json

{
  "username": "MahaDevi",
  "name": "Adam Richard",
  "password": "devi123",
  "gender": "male",
  "location": "Detroit"
}
###
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "MahaDevi",
  "password": "devi123"
}

###
put http://localhost:3000/change-password
Content-Type: application/json 

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "rich12345"
}